import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1A3561",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    paddingTop: "25vh",
  },
  backArrow: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: "10vh",
    left: "20px",
  },
  button: {
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: "60%",
    height: 40,
    borderRadius: 10,
    marginTop: "5vh",
    position: "relative",
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "black",
    fontStyle: "italic",
    fontFamily: "kalam",
  },
  forgotPassButton: {
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: "100%",
    height: 40,
    borderRadius: 5,
    marginTop: "5vh",
    position: "relative",
    fontStyle: "italic",
    fontFamily: "kalam",
  },
  textInput: {
    fontStyle: "italic",
    fontFamily: "kalam",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: "60%",
    height: 40,
    borderRadius: 5,
    marginTop: "5vh",
    position: "relative",
  },
  underline: {
    color: "#6DB5C4",
    textAlign: "left",
    fontStyle: "italic",
    fontFamily: "kalam",
    paddingTop: "5px",
  },
  forgotPassword: {
    width: "60%",
    fontStyle: "italic",
    fontFamily: "kalam",
  },
  messageContainer: {
    display: "flex",
    position: "absolute",
    zIndex: 99,
    top: "20vh",
    width: "60%",
    backgroundColor: "white",
    left: "20%",
    borderRadius: 10,
    padding: "15px",
    textAlign: "center",
  },
  goodMessage: {
    color: "green",
  },
  badMessage: {
    color: "red",
  },
  text: {},
  rootContainer: {
    height: "100vh",
    width: "100vw",
    margin: "0",
  },
});

export { styles };
