import { StyleSheet, Dimensions } from "react-native";
var { height, width } = Dimensions.get("window");
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1A3561",
    alignItems: "center",
    justifyContent: "center",
    width: width,
    paddingTop: height * 0.25,
  },
  backArrow: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: height * 0.1,
    left: 20,
  },
  button: {
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: width * 0.6,
    height: 40,
    borderRadius: 10,
    marginTop: height * 0.05,
    position: "relative",
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "black",
    fontStyle: "italic",
  },
  forgotPassButton: {
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: width * 0.6,
    height: 40,
    borderRadius: 5,
    marginTop: height * 0.05,
    position: "relative",
    fontStyle: "italic",
  },
  textInput: {
    fontStyle: "italic",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: width * 0.6,
    height: 40,
    borderRadius: 5,
    marginTop: height * 0.05,
    position: "relative",
    paddingLeft: 5,
  },
  underline: {
    color: "#6DB5C4",
    textAlign: "left",
    fontStyle: "italic",
    paddingTop: 5,
  },
  forgotPassword: {
    width: width * 0.6,
    fontStyle: "italic",
  },
  messageContainer: {
    display: "flex",
    position: "absolute",
    zIndex: 99,
    top: height * 0.2,
    width: width * 0.6,
    backgroundColor: "white",
    left: width * 0.2,
    borderRadius: 10,
    padding: 15,
    textAlign: "center",
  },
  goodMessage: {
    color: "green",
  },
  badMessage: {
    color: "red",
  },
  text: {},
  rootContainer: {
    height: height,
    width: width,
    margin: 0,
  },
  containerPrivate: {
    flex: 1,
    backgroundColor: "#1A3561",
    alignItems: "center",
    justifyContent: "center",
    width: width,
  },
  contentContainer: {
    flex: 9,
    backgroundColor: "#1A3561",
    alignItems: "center",
    justifyContent: "center",
    width: width,
  },
  pane: {
    flex: 1,
    backgroundColor: "#1A3561",
    width: width,
    height: height * 0.9,
  },
  navbarButton: {
    width: width * 0.2,
    height: height * 0.1,
    display: "flex",
    justifyContent: "center",
    borderBottomWidth: 2,
    borderColor: "gray",
    borderStyle: "solid",
  },
  activeNavbarButton: {
    width: width * 0.2,
    borderBottomWidth: 4,
    borderColor: "black",
    borderStyle: "solid",
    textAlign: "center",
    height: height * 0.1,
    display: "flex",
    justifyContent: "center",
  },
  navbarText: {
    textAlign: "center",
    fontStyle: "italic",
  },
  navbar: {
    flex: 1,
    flexDirection: "row",
    width: width,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 1,
    borderTopColor: "#1A3561",
  },
  topRightIcon: {
    position: "absolute",
    right: width * 0.02,
    top: height * 0.02,
  },
  topLeftIcon: {
    position: "absolute",
    left: width * 0.02,
    top: height * 0.02,
  },
  settingsOptionsContainer: {
    width,
    marginTop: height * 0.1,
    height: height * 0.8,
  },
  settingsOption: {
    width: width * 0.8,
    marginLeft: width * 0.1,
    height: height * 0.15,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: "#1A3561",
    borderStyle: "solid",
    backgroundColor: "white",
    paddingLeft: width * 0.05,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  logoutIcon: {
    paddingRight: 15,
  },
  recordingPeopleContainer: {
    paddingTop: height * 0.08,
    height: height * 0.4,
  },
  recordingClipsContainer: {
    height: height * 0.29,
  },
  recordingIconsContainer: {
    height: height * 0.21,
    width: width,
    flexDirection: "row",
  },
  iconSmallContainer: {
    width: width * 0.15,
    justifyContent: "center",
    alignItems: "center",
  },
  iconContainer: {
    width: width * 0.7,
    justifyContent: "center",
    alignItems: "center",
  },
  recordingMicIcon: {
    paddingLeft: 10,
    paddingBottom: 10,
    fontSize:
      width * 0.24 < (height * 0.21) / 1.7 - 10
        ? width * 0.24
        : (height * 0.21) / 1.7 - 10,
  },
  recordingCircleIcon: {
    fontSize:
      width * 0.16 < (height * 0.21) / 2.5 - 10
        ? width * 0.16
        : (height * 0.21) / 2.5 - 10,
  },
  recordingHashtagIcon: {
    paddingRight: 20,
    fontSize: width * 0.1 < 50 ? width * 0.1 : 50,
  },
  recordingFireIcon: {
    paddingLeft: 20,
    fontSize: width * 0.1 < 50 ? width * 0.1 : 50,
  },
});

export { styles };
