import { Dimensions, Platform, PixelRatio, StyleSheet } from "react-native";
var { height, width } = Dimensions.get("window");
// based on iphone 5s's scale
const scale = width / 320;

export function normalize(size) {
  const newSize = size * scale;
  if (Platform.OS === "ios") {
    return Math.round(PixelRatio.roundToNearestPixel(newSize));
  } else {
    return Math.round(PixelRatio.roundToNearestPixel(newSize)) - 2;
  }
}

const mini = normalize(12);
const small = normalize(15);
const medium = normalize(17);
const large = normalize(20);
const xl = normalize(24);
const postHeight = width > 1000 ? height * 0.35 : height * 0.23;
const postPadding = height * 0.02;
const chatWidth = width * 0.8;
const filterHeight = height * 0.2;
const postWidth = width > 1000 ? width * 0.8 : width;
const listItemHeight = height * 0.08;
const listItemHeight2X = listItemHeight * 2;
const contentPaneHeight = height * 0.875;
const contentPaneWithHeaderHeight = height * 0.775;
const largeIconFontSize =
  width * 0.24 < (height * 0.21) / 1.7 - 10
    ? width * 0.24
    : (height * 0.21) / 1.7 - 10;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
    width: width,
    paddingTop: height * 0.25,
  },
  commentsContainer: {
    flex: 10,
  },
  avoidingView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  searchTags: {
    display: "flex",
    flexDirection: "column",
    width,
    flex: 1,
    justifyContent: "space-evenly",
  },
  appBarHeader: {
    width,
    height: height * 0.1,
    zIndex: 51,
  },
  recordingContainerComments: {
    width,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 10,
    borderTopColor: "black",
    borderStyle: "solid",
    borderTopWidth: 1,
    marginTop: 10,
    backgroundColor: "white",
  },
  chatPane: {
    display: "flex",
    flex: 1,
  },
  recordingContainerChat: {
    width,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 10,
    borderTopColor: "black",
    borderStyle: "solid",
    borderTopWidth: 1,
    marginTop: 10,
    backgroundColor: "white",
  },
  textInputComments: {
    borderWidth: 2,
    borderColor: "#000000",
    borderStyle: "solid",
    flex: 7,
  },
  iconContainerComments: {
    flex: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  commentParent: {},
  commentOpenContainer: {
    backgroundColor: "white",
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "black",
    borderRadius: 8,
    width: width > 1000 ? width * 0.6 : width,
    position: "relative",
    flex: 1,
    zIndex: 3,
    top: 0,
    left: 0,
  },
  backArrow: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: height * 0.1,
    left: 20,
  },
  button: {
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: width * 0.6,
    borderRadius: 10,
    marginTop: height * 0.05,
    position: "relative",
    fontStyle: "italic",
  },
  forgotPassButton: {
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: width * 0.6,
    height: 40,
    borderRadius: 5,
    marginTop: height * 0.05,
    marginBottom: height * 0.02,
    position: "relative",
    fontStyle: "italic",
  },
  textInput: {
    fontStyle: "italic",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: width * 0.6,
    height: 40,
    borderRadius: 5,
    marginTop: height * 0.05,
    marginBottom: height * 0.02,
    position: "relative",
    paddingLeft: 5,
  },
  textInputRecEdit: {
    fontStyle: "italic",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    borderBottomColor: "white",
    borderStyle: "solid",
    borderBottomWidth: 1,
    width: width * 0.6,
    height: 40,
    borderRadius: 5,
    marginTop: height * 0.05,
    position: "relative",
    paddingLeft: 5,
    fontSize: small,
  },
  profileText: {
    width: width * 0.6,
    textAlign: "center",
    marginTop: 5,
    fontStyle: "italic",
    color: "#30F3FF",
    fontSize: small,
  },
  invalidTextInput: {
    fontSize: small,
    fontStyle: "italic",
    backgroundColor: "#FFFFFF",
    borderColor: "red",
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    color: "red",
    width: width * 0.6,
    height: 40,
    borderRadius: 5,
    marginTop: height * 0.05,
    position: "relative",
    paddingLeft: 5,
  },
  underline: {
    color: "#6DB5C4",
    textAlign: "left",
    fontStyle: "italic",
    paddingTop: 5,
    fontSize: small,
  },
  forgotPassword: {
    width: width * 0.6,
    fontStyle: "italic",
    fontSize: small,
  },
  messageContainer: {
    display: "flex",
    position: "absolute",
    zIndex: 99,
    top: height * 0.2,
    width: width * 0.6,
    backgroundColor: "white",
    left: width * 0.2,
    borderRadius: 10,
    padding: 15,
    textAlign: "center",
  },
  goodMessage: {
    color: "green",
  },
  badMessage: {
    color: "red",
  },
  text: {},
  whiteText: {
    color: "white",
  },
  blackText: {
    color: "black",
    fontStyle: "italic",
  },
  rootContainer: {
    height: height,
    width: width,
    margin: 0,
    overflow: "visible",
  },
  containerPrivate: {
    flex: 1,
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
    width: width,
  },
  contentContainer: {
    flex: 9,
    backgroundColor: "#000000",
    alignItems: "center",
    justifyContent: "center",
    width: width,
  },
  pane: {
    flex: 1,
    backgroundColor: "#000000",
    width: width,
    height: contentPaneHeight,
    justifyContent: "center",
    alignItems: "center",
  },
  paneSpaceEvenly: {
    flex: 1,
    backgroundColor: "#000000",
    width: width,
    height: contentPaneHeight,
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  paneUncentered: {
    flex: 1,
    backgroundColor: "#000000",
    width: width,
    height: contentPaneHeight,
  },
  profileHeader: {
    width,
    paddingTop: height * 0.025,
    alignItems: "center",
    paddingBottom: 10,
  },
  bioHeader: {
    position: "absolute",
    left: 0,
    paddingLeft: width * 0.05,
    color: "white",
    fontStyle: "italic",
    fontSize: small,
  },
  bioContainer: {
    width,
    alignItems: "center",
    justifyContent: "center",
    marginTop: height * 0.0125,
  },
  subBioContainer: {
    marginTop: height * 0.0125,
    flexDirection: "row",
    width: width * 0.8,
    justifyContent: "space-evenly",
  },
  navbarButton: {
    width: width * 0.2,
    height: height * 0.1,
    display: "flex",
    justifyContent: "center",
  },
  activeNavbarButton: {
    width: width * 0.2,
    color: "#6FF6FF",
    textAlign: "center",
    height: height * 0.1,
    display: "flex",
    justifyContent: "center",
  },
  navbarText: {
    textAlign: "center",
    fontStyle: "italic",
    fontSize: small,
  },
  navbar: {
    flexDirection: "row",
    width: width,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    borderTopWidth: 1,
    borderTopColor: "#000000",
    height: height * 0.125,
  },
  modalContainer: {
    zIndex: 998,
    position: "absolute",
    width,
    height,
    backgroundColor: "rgba(0,0,0,0.5)",
    bottom: 0,
  },
  modalMainContainer: {
    zIndex: 999,
    backgroundColor: "white",
    width: width * 0.5,
    height: height * 0.25,
    marginHorizontal: width * 0.25,
    marginVertical: height * 0.375,
    justifyContent: "space-evenly",
    alignItems: "center",
    flexDirection: "row",
    borderRadius: 20,
  },
  uploadIcon: {
    position: "absolute",
    bottom: 0,
    right: 10,
    fontSize: medium,
  },
  topLeftIcon: {
    position: "absolute",
    left: width * 0.08,
    top: height * 0.08,
  },
  toptopLeftIcon: {
    position: "absolute",
    left: width * 0.08,
    top: height * 0.08,
  },
  topRightIcon: {
    position: "absolute",
    right: width * 0.08,
    top: height * 0.08,
    zIndex: 2,
  },
  toptopRightIcon: {
    position: "absolute",
    right: width * 0.08,
    top: height * 0.08,
    zIndex: 2,
  },
  largeIcon: {
    fontSize: xl,
  },
  settingsOptionsContainer: {
    width,
    marginTop: height * 0.125,
    height: height * 0.8,
  },
  settingsOption: {
    width: width * 0.8,
    marginLeft: width * 0.1,
    height: height * 0.15,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: "#000000",
    borderStyle: "solid",
    backgroundColor: "white",
    paddingLeft: width * 0.05,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  logoutIcon: {
    paddingRight: 15,
  },
  recordingPeopleContainer: {
    flex: 3,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width,
  },
  postsContainer: {
    marginTop: height * 0.015,
    width: width > 1000 ? width * 0.8 : width,
    height: width > 1000 ? height * 0.25 : "auto",
    margin: "auto",
    paddingBottom: height * 0.4,
  },
  refresh: {
    backgroundColor: "black",
    position: "absolute",
    top: 0,
    width,
    justifyContent: "center",
    alignItems: "center",
    height: height * 0.05,
    zIndex: 99,
  },
  deleteItemContainer: {
    flexDirection: "row",
    justifyContent: "center",
    flexWrap: "wrap",
    alignItems: "flex-start",
    minHeight: 0,
    paddingBottom: 20,
    maxHeight: height * 0.2,
    overflow: "scroll",
  },
  tagTitle: {
    fontWeight: "700",
    fontStyle: "italic",
    fontSize: large,
  },
  postContainer: {
    height: postHeight,
    width: postWidth,
    borderRadius: 8,
    borderWidth: 2,
    marginBottom: postPadding,
    backgroundColor: "white",
    justifyContent: "center",
    paddingHorizontal: 15,
    flexDirection: "row",
    position: "relative",
    paddingVertical: 10,
    overflow: "scroll",
  },
  notif: {
    borderRadius: 8,
    borderWidth: 2,
    marginBottom: postPadding,
    backgroundColor: "white",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingHorizontal: 15,
    flexDirection: "row",
    position: "relative",
    paddingVertical: 10,
    overflow: "scroll",
  },
  higherPostContainer: {
    height: postHeight,
    width: postWidth,
    borderRadius: 8,
    borderWidth: 2,
    marginBottom: height * 0.02,
    backgroundColor: "white",
    justifyContent: "center",
    paddingHorizontal: 15,
    flexDirection: "row",
    position: "relative",
    zIndex: 1,
  },
  recordingMicIconComments: {
    fontSize: large,
  },
  currentRecordingIconComments: {
    fontSize: large,
  },
  postTitle: {
    fontStyle: "italic",
    fontSize: width > 1000 ? medium : large,
    fontWeight: "700",
  },
  textAndPlayButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  postText: {
    flex: 9,
  },
  postPlayButton: {
    justifyContent: "center",
    alignItems: "center",
  },
  likesText: {
    fontSize: small,
    lineHeight: small,
    textAlign: "center",
  },
  recordingClipsContainer: {
    flex: 4,
    width: width < 1000 ? width * 0.95 : width * 0.8,
  },
  recordingIconsContainer: {
    flex: 3,
    width: width,
    flexDirection: "row",
  },
  iconSmallContainer: {
    width: width * 0.15,
    justifyContent: "center",
    alignItems: "center",
  },
  iconContainer: {
    width: width * 0.7,
    justifyContent: "center",
    alignItems: "center",
  },
  recordingMicIcon: {
    paddingLeft: 10,
    fontSize: largeIconFontSize,
  },
  currentRecordingIcon: {
    fontSize: largeIconFontSize,
  },
  recordingCircleIcon: {
    fontSize:
      width * 0.16 < (height * 0.21) / 2.5 - 10
        ? width * 0.16
        : (height * 0.21) / 2.5 - 10,
  },
  recordingHashtagIcon: {
    paddingRight: 20,
    fontSize: width * 0.1 < 50 ? width * 0.1 : 50,
  },
  recordingFireIcon: {
    paddingLeft: 20,
    fontSize: width * 0.1 < 50 ? width * 0.1 : 50,
  },
  commentActionsDiv: {
    flexDirection: "row",
    borderLeftColor: "#000000",
    borderStyle: "solid",
    borderLeftWidth: 1,
  },
  replyActionsText: {
    fontStyle: "italic",
    paddingLeft: 15,
  },
  profileImgContainer: {
    width: height * 0.2,
    borderRadius: height * 0.2,
    overflow: "hidden",
  },
  commentContainer: {
    marginTop: height * 0.02,
    height: height * 0.06,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    flexDirection: "row",
    borderLeftColor: "#000000",
    borderStyle: "solid",
    borderLeftWidth: 1,
  },
  commentImgContainer: {
    height: height * 0.05,
    width: height * 0.05,
    borderRadius: height * 0.05,
    overflow: "hidden",
    resizeMode: "cover",
  },
  commentImg: {
    height: height * 0.05,
    width: height * 0.05,
    borderRadius: height * 0.05,
  },
  profileImg: {
    height: height * 0.2,
    width: height * 0.2,
    borderRadius: height * 0.2,
  },
  profileImgContainerSmall: {
    height: height * 0.15,
    width: height * 0.15,
    borderRadius: height * 0.15,
    overflow: "hidden",
  },
  profileImgSmall: {
    height: height * 0.15,
    width: height * 0.15,
    borderRadius: height * 0.15,
  },
  messagesParentContainer: {
    paddingTop: height * 0.01,
    flex: 6,
  },
  messagesContainer: {
    flexDirection: "column",
  },
  userChat: {
    left: 0,
    backgroundColor: "white",
    width: chatWidth,
    flexDirection: "column",
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
    marginLeft: width * 0.05,
  },
  foreignChat: {
    marginLeft: width * 0.15,
    backgroundColor: "gray",
    width: chatWidth,
    flexDirection: "column",
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
  },
  messageMember: {
    alignItems: "center",
  },
  parentViewStyleUsers: {
    top: 16,
    position: "absolute",
  },
  listItemProfileImg: {
    height: height * 0.05,
    width: height * 0.05,
    borderRadius: height * 0.05,
  },
  upperEditDiv: {
    marginTop: height * 0.05,
    height: height * 0.15,
  },
  upperEditDivAbsolute: {
    height: height * 0.15,
    zIndex: 3,
    justifyContent: "space-evenly",
  },
  clipsEditDiv: {
    height: height * 0.3,
    width: width * 0.95,
  },
  filterEditDiv: {
    height: filterHeight,
    width: width * 0.95,
    backgroundColor: "white",
  },
  continueEditDiv: {
    height: height * 0.18,
    justifyContent: "center",
    alignItems: "center",
  },
  nextButton: {
    height: width * 0.075,
    width: width * 0.3,
    minHeight: 50,
    maxHeight: 200,
    borderWidth: 1,
    borderRadius: 4,
    borderColor: "white",
    borderStyle: "solid",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  smallNextButton: {
    height: width * 0.05,
    flex: 1,
    marginHorizontal: 10,
    minHeight: 50,
    maxHeight: 200,
    borderWidth: 1,
    borderRadius: 4,
    borderColor: "white",
    borderStyle: "solid",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
    textAlign: "center",
  },
  nextButtonBio: {
    height: width * 0.075,
    flex: 1,
    minHeight: 50,
    maxHeight: 200,
    borderWidth: 1,
    borderRadius: 4,
    borderColor: "white",
    borderStyle: "solid",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  imageAndFollowing: {
    flexDirection: "row",
    alignItems: "center",
  },
  followersText: {
    paddingLeft: 20,
    fontSize: 20,
    color: "white",
  },
  playButtonContainerBio: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  nextButtonText: {
    color: "black",
    fontStyle: "italic",
    fontSize: small,
    fontWeight: "600",
  },
  recordingSettings: {
    maxHeight: height * 0.3,
    width: width * 0.95,
    borderRadius: 3,
  },
  recordingSettingsOption: {
    height: listItemHeight,
    width: width * 0.95,
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#000000",
    borderStyle: "solid",
    alignItems: "center",
    borderRadius: 20,
    paddingHorizontal: 20,
  },
  playButtonContainer: {
    height: height * 0.1,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  playButton: {
    fontSize: large,
  },
  continueButtonContainer: {
    height: height * 0.1,
    flexDirection: "row",
    width: width * 0.7,
    justifyContent: "space-between",
    alignItems: "center",
  },
  resultsContainer: {
    zIndex: 2,
    flexDirection: "row",
    maxHeight: height * 0.35,
    backgroundColor: "white",
    width: width * 0.6,
    borderRadius: 8,
  },
  searchResultsContainer: {
    height: height * 0.8,
  },
  tagResultsContainer: {
    flex: 1,
    marginTop: height * 0.05,
    marginBottom: 20,
  },
  userResultsContainer: {
    flex: 6,
  },
  foreignProfileButtons: {
    marginTop: height * 0.02,
    flexDirection: "row",
    justifyContent: "space-evenly",
    width: width,
  },
  listItemContainer: {
    height: listItemHeight,
    borderColor: "#000000",
    borderWidth: 2,
    borderStyle: "solid",
    padding: 10,
    backgroundColor: "white",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    width: width * 0.6,
  },
  listItemContainerUser: {
    height: listItemHeight,
    borderColor: "#000000",
    borderWidth: 2,
    borderStyle: "solid",
    padding: 10,
    backgroundColor: "white",
    flexDirection: "row",
    width,
    justifyContent: "flex-start",
    alignItems: "center",
    borderRadius: 8,
  },
  listItemContainerChat: {
    height: height * 0.1,
    borderColor: "#000000",
    borderWidth: 2,
    borderRadius: 8,
    paddingVertical: 10,
    borderStyle: "solid",
    padding: 10,
    backgroundColor: "white",
    flexDirection: "row",
    width,
    justifyContent: "flex-start",
    alignItems: "center",
  },
  listItemTextUser: {
    fontSize: medium,
    paddingLeft: 10,
  },
  promptText: {
    marginVertical: 20,
    fontStyle: "italic",
    fontSize: large,
    color: "black",
    marginRight: 8,
  },
  promptTopic: {
    flexDirection: "row",
    alignItems: "center",
    position: "absolute",
    width: width * 0.9,
    backgroundColor: "white",
    left: width * 0.05,
    borderRadius: 24,
    zIndex: 2,
  },
  deletePromptButton: {
    marginHorizontal: 8,
  },
  loadingContainer: {
    height,
    width: width * 0.3,
    left: width * 0.35,
    position: "absolute",
    justifyContent: "center",
    zIndex: 67,
    alignItems: "center",
  },
});

const listStyles = StyleSheet.create({
  container: {
    backgroundColor: "white",
    flex: 1,
  },
  backTextWhite: {
    color: "#FFF",
  },
  rowFront: {
    alignItems: "center",
    backgroundColor: "#CCC",
    borderBottomColor: "black",
    borderBottomWidth: 1,
    justifyContent: "center",
    height: 50,
  },
  rowBack: {
    alignItems: "center",
    backgroundColor: "transparent",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: 15,
    right: 0,
    width,
  },
  backRightBtn: {
    alignItems: "center",
    bottom: 0,
    justifyContent: "center",
    position: "absolute",
    top: 0,
    width: 75,
    borderWidth: 2,
    zIndex: -1,
  },
  backRightBtnRight: {
    backgroundColor: "white",
    right: 0,
    height: postHeight,
    borderRadius: 8,
  },
});

export {
  styles,
  postPadding,
  postHeight,
  filterHeight,
  largeIconFontSize,
  postWidth,
  small,
  medium,
  large,
  listItemHeight,
  listItemHeight2X,
  listStyles,
  chatWidth,
};
