import { StyleSheet, Dimensions } from "react-native";
var { height, width } = Dimensions.get("window");
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1A3561",
    alignItems: "center",
    justifyContent: "center",
    width: width,
    paddingTop: height * 0.25,
  },
  backArrow: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: height * 0.1,
    left: 20,
  },
  button: {
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: width * 0.6,
    height: 40,
    borderRadius: 10,
    marginTop: height * 0.05,
    position: "relative",
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "black",
    fontStyle: "italic",
  },
  forgotPassButton: {
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: width * 0.6,
    height: 40,
    borderRadius: 5,
    marginTop: height * 0.05,
    position: "relative",
    fontStyle: "italic",
  },
  textInput: {
    fontStyle: "italic",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    color: "black",
    width: width * 0.6,
    height: 40,
    borderRadius: 5,
    marginTop: height * 0.05,
    position: "relative",
  },
  underline: {
    color: "#6DB5C4",
    textAlign: "left",
    fontStyle: "italic",
    paddingTop: 5,
  },
  forgotPassword: {
    width: width * 0.6,
    fontStyle: "italic",
  },
  messageContainer: {
    display: "flex",
    position: "absolute",
    zIndex: 99,
    top: height * 0.2,
    width: width * 0.6,
    backgroundColor: "white",
    left: width * 0.2,
    borderRadius: 10,
    padding: 15,
    textAlign: "center",
  },
  goodMessage: {
    color: "green",
  },
  badMessage: {
    color: "red",
  },
  text: {},
  rootContainer: {
    height: height,
    width: width,
    margin: 0,
  },
  containerPrivate: {
    flex: 1,
    backgroundColor: "#1A3561",
    alignItems: "center",
    justifyContent: "center",
    width: width,
  },
  contentContainer: {
    flex: 9,
    backgroundColor: "#1A3561",
    alignItems: "center",
    justifyContent: "center",
    width: width,
  },
  navbarButton: {
    width: width * 0.2,
    height: height * 0.1,
    display: "flex",
    justifyContent: "center",
    borderBottomWidth: 2,
    borderColor: "gray",
    borderStyle: "solid",
  },
  activeNavbarButton: {
    width: width * 0.2,
    borderBottomWidth: 4,
    borderColor: "black",
    borderStyle: "solid",
    textAlign: "center",
    height: height * 0.1,
    display: "flex",
    justifyContent: "center",
  },
  navbarText: {
    textAlign: "center",
    fontStyle: "italic",
  },
  navbar: {
    flex: 1,
    flexDirection: "row",
    width: width,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
  },
});

export { styles };
